### ISSUE TITLE
-123-the-ocicats

### ISSUE THREAD

**Issue by atenaiis** [MarilenaRoque/JoyStickedExperience#1]
* To work on the footer, make the icons smaller
* To change the mobile main program instead of rows to columns 

***Do not stress you are doing a great job**

**Comment by MarilenaRoque** [comment]
Thank you so much for the review and ideas guys.

- I have removed the responsiveness for the footer and now the icons are small In both versions
- I needed to keep the Main Program items in rows to keep the design similarity with the design, but I applied the other tip to centralize it and it looks awesome.
